[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
redb = "2.5.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["sync", "macros", "rt"] }

[dev-dependencies]
tempfile = "3.19.1"
